In [1]:
import pandas as pd

In [5]:
data={'Hours Studied':[1,2,3,4,5,6,7,8,9,10],'Passed':[0,0,0,0,1,1,1,1,1,1]}

In [6]:
data

{'Hours Studied': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
 'Passed': [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]}

In [7]:
df = pd.DataFrame(data)

In [8]:
df

   Hours Studied  Passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       1
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [9]:
X = df[['Hours Studied']]
print(X)

   Hours Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [10]:
y = df['Passed']
print(y)

0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
8    1
9    1
Name: Passed, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [17]:
print("X_train:")
print(X_train)

print("\nX_test:")
print(X_test)

print("\ny_train:")
print(y_train)

print("\ny_test:")
print(y_test)

X_train:
   Hours Studied
4              5
9             10
1              2
6              7
7              8
3              4
0              1
5              6

X_test:
   Hours Studied
2              3
8              9

y_train:
4    1
9    1
1    0
6    1
7    1
3    0
0    0
5    1
Name: Passed, dtype: int64

y_test:
2    0
8    1
Name: Passed, dtype: int64

In [18]:
# Import Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
# Create and Train model

In [22]:
model=LogisticRegression()

In [23]:
model.fit(X_train,y_train)

LogisticRegression()

In [24]:
#Prediction

In [25]:
y_pred=model.predict(X_test)

In [26]:
y_pred

array([0, 1])

In [27]:
X_test

   Hours Studied
2              3
8              9

In [28]:
y_test

2    0
8    1
Name: Passed, dtype: int64

In [33]:
hours = float(input("Enter Hours Studied: "))

new_data = pd.DataFrame({'Hours Studied': [hours]})

prediction = model.predict(new_data)

if prediction[0] == 1:
    print("Passed")
else:
    print("Not Passed")

Enter Hours Studied:  7.5

Passed

In [36]:
y_pred = model.predict(X_test)

difference = y_test.values - y_pred

print("Difference (Actual - Predicted):")
print(difference)

Difference (Actual - Predicted):
[0 0]

In [37]:
difference = y_test - y_pred
print(difference)

2    0
8    0
Name: Passed, dtype: int64

In [38]:
y_prob=model.predict_proba(X_test)

In [39]:
y_prob

array([[0.80074986, 0.19925014],
       [0.00628993, 0.99371007]])